import { GlobalThemeWrapper } from '@/lib/globalTheme';
import { ReactQueryProvider } from '@/lib/reactQueryProvider';
import StyledComponentsRegistry from '@/lib/registry';
import type { Metadata } from 'next';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryProvider>
      <StyledComponentsRegistry>
        <GlobalThemeWrapper>
          <html lang='en'>
            <body>
              {children}
            </body>
          </html>
        </GlobalThemeWrapper>
      </StyledComponentsRegistry>
    </ReactQueryProvider>
  );
}
