import { GlobalThemeWrapper } from '@/lib/globalTheme';
import { ReactQueryProvider } from '@/lib/reactQueryProvider';
import { ReduxProvider } from '@/lib/reduxProvider';
import StyledComponentsRegistry from '@/lib/registry';
import type { Metadata } from 'next';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryProvider>
      <StyledComponentsRegistry>
        <GlobalThemeWrapper>
          <html lang='en'>
            <ReduxProvider>
              <body>
                {children}
              </body>
            </ReduxProvider>
          </html>
        </GlobalThemeWrapper>
      </StyledComponentsRegistry>
    </ReactQueryProvider>
  );
}
